const savedInventory = {
    test: [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 9
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 10
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 11
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 12
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 13
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 14
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 15
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 16
            },
            {
                type: 170,
                count: 23,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 17
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 18
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 19
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 20
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 21
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 22
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 23
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 24
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 25
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 26
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 27
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 28
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 29
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 30
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 31
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 32
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 33
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 34
            },
            {
                type: 170,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'obsidian',
                displayName: 'Obsidian',
                stackSize: 64,
                maxDurability: undefined,
                slot: 35
            },
            {
                type: 611,
                count: 1,
                metadata: 0,
                nbt: {type: 'compound', name: '', value: [Object]},
                stackId: null,
                name: 'netherite_axe',
                displayName: 'Netherite Axe',
                stackSize: 1,
                maxDurability: 2031,
                slot: 36
            },
            {
                type: 277,
                count: 1,
                metadata: 0,
                nbt: null,
                stackId: null,
                name: 'ender_chest',
                displayName: 'Ender Chest',
                stackSize: 64,
                maxDurability: undefined,
                slot: 37
            },
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ]
}





export default savedInventory